---
# App defaults
app_name: "{{ lookup('env', 'APP_NAME') or 'tackle' }}"
app_namespace: "{{ lookup('env', 'WATCH_NAMESPACE') or 'konveyor-tackle' }}"
app_profile: "{{ lookup('env', 'PROFILE') }}"
app_version: "{{ lookup('env', 'VERSION') }}"

# Feature defaults
feature_ui_enabled: true
feature_auth_required: true
feature_isolate_namespace: true
feature_auth_provider: "keycloak"

openshift_cluster: false
image_pull_policy: "Always"
tackle_operator_version: "latest"
tackle_resources:
  - "Deployment"
  - "ConfigMap"
  - "Secret"
  - "Route"

# Components
hub_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_TACKLE_HUB') }}"
hub_component_name: "hub"
hub_service_name: "{{ app_name }}-{{ hub_component_name }}"
hub_serviceaccount_name: "{{ app_name }}-hub"
hub_configmap_name: "{{ hub_service_name }}-config"
hub_secret_name: "{{ hub_service_name }}"
hub_deployment_name: "{{ hub_service_name }}"
hub_deployment_replicas: "1"
hub_deployment_strategy: "Recreate"
hub_container_name: "{{ hub_service_name }}"
hub_container_limits_cpu: "500m"
hub_container_limits_memory: "800Mi"
hub_container_requests_cpu: "100m"
hub_container_requests_memory: "350Mi"
hub_database_filename: "hub.db"
hub_database_volume_name: "{{ hub_service_name }}-database"
hub_database_volume_size: "5Gi"
hub_database_volume_path: "/database"
hub_database_volume_claim_name: "{{ hub_service_name }}-database-volume-claim"
hub_bucket_volume_name: "{{ hub_service_name }}-bucket"
hub_bucket_volume_size: "100Gi"
hub_bucket_volume_path: "/buckets"
hub_bucket_volume_claim_name: "{{ hub_service_name }}-bucket-volume-claim"
hub_seed_configmap_name: "{{ hub_service_name }}-seed"
hub_seed_configmap_path: "/seed"
hub_addon_working_path: "/working"
hub_task_sa: "tackle-hub"
hub_tls_enabled: false
hub_tls_secret_name: "{{ hub_service_name }}-serving-cert"
hub_log_level: 3

pathfinder_database_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_PATHFINDER_DATABASE') }}"
pathfinder_database_name: "pathfinder"
pathfinder_database_component_name: "postgresql"
pathfinder_database_service_name: "{{ app_name }}-{{ pathfinder_database_name }}-{{ pathfinder_database_component_name }}"
pathfinder_database_secret_name: "{{ pathfinder_database_service_name }}"
pathfinder_database_deployment_name: "{{ pathfinder_database_service_name }}"
pathfinder_database_deployment_strategy: "Recreate"
pathfinder_database_deployment_replicas: "1"
pathfinder_database_container_name: "{{ pathfinder_database_service_name }}"
pathfinder_database_container_limits_cpu: "500m"
pathfinder_database_container_limits_memory: "800Mi"
pathfinder_database_container_requests_cpu: "100m"
pathfinder_database_container_requests_memory: "350Mi"
pathfinder_database_data_volume_name: "{{ pathfinder_database_service_name }}-database"
pathfinder_database_data_volume_size: "1Gi"
pathfinder_database_data_volume_path: "/var/lib/pgsql"
pathfinder_database_data_volume_claim_name: "{{ pathfinder_database_service_name }}-volume-claim"
pathfinder_database_db_name: "pathfinder_db"
pathfinder_database_db_name_b64: "{{ pathfinder_database_db_name | b64encode }}"

pathfinder_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_PATHFINDER') }}"
pathfinder_component_name: "pathfinder"
pathfinder_service_name: "{{ app_name }}-{{ pathfinder_component_name }}"
pathfinder_deployment_name: "{{ pathfinder_service_name }}"
pathfinder_deployment_replicas: "1"
pathfinder_container_name: "{{ pathfinder_service_name }}"
pathfinder_container_limits_cpu: "1000m"
pathfinder_container_limits_memory: "2Gi"
pathfinder_container_requests_cpu: "100m"
pathfinder_container_requests_memory: "350Mi"
pathfinder_tls_enabled: false
pathfinder_tls_secret_name: "{{ pathfinder_service_name }}-serving-cert"

keycloak_database_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_KEYCLOAK_DATABASE') }}"
keycloak_database_name: "keycloak"
keycloak_database_component_name: "postgresql"
keycloak_database_service_name: "{{ app_name }}-{{ keycloak_database_name }}-{{ keycloak_database_component_name }}"
keycloak_database_secret_name: "{{ keycloak_database_service_name }}"
keycloak_database_deployment_name: "{{ keycloak_database_service_name }}"
keycloak_database_deployment_strategy: "Recreate"
keycloak_database_deployment_replicas: "1"
keycloak_database_container_name: "{{ keycloak_database_service_name }}"
keycloak_database_container_limits_cpu: "500m"
keycloak_database_container_limits_memory: "800Mi"
keycloak_database_container_requests_cpu: "100m"
keycloak_database_container_requests_memory: "350Mi"
keycloak_database_data_volume_name: "{{ keycloak_database_service_name }}-database"
keycloak_database_data_volume_size: "1Gi"
keycloak_database_data_volume_path: "/var/lib/pgsql"
keycloak_database_data_volume_claim_name: "{{ keycloak_database_service_name }}-volume-claim"
keycloak_database_db_name: "keycloak_db"
keycloak_database_db_name_b64: "{{ keycloak_database_db_name | b64encode }}"

keycloak_sso_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_KEYCLOAK_SSO') }}"
keycloak_sso_name: "keycloak"
keycloak_sso_component_name: "sso"
keycloak_sso_service_name: "{{ app_name }}-{{ keycloak_sso_name }}-{{ keycloak_sso_component_name }}"
keycloak_sso_configmap_name: "{{ keycloak_sso_service_name }}"
keycloak_sso_secret_name: "{{ keycloak_sso_service_name }}"
keycloak_sso_deployment_name: "{{ keycloak_sso_service_name }}"
keycloak_sso_deployment_replicas: "1"
keycloak_sso_container_name: "{{ keycloak_sso_service_name }}"
keycloak_sso_container_limits_cpu: "1000m"
keycloak_sso_container_limits_memory: "2Gi"
keycloak_sso_container_requests_cpu: "300m"
keycloak_sso_container_requests_memory: "600Mi"
keycloak_sso_liveness_init_delay: "60"
keycloak_sso_readiness_init_delay: "60"
keycloak_sso_tls_enabled: false
keycloak_sso_tls_secret_name: "{{ keycloak_sso_service_name }}-serving-cert"
keycloak_sso_admin_username: "admin"
keycloak_sso_admin_username_b64: "{{ keycloak_sso_admin_username | b64encode }}"
keycloak_sso_java_opts: "-Dcom.redhat.fips=false"
keycloak_sso_host: "http://{{ keycloak_sso_service_name }}.{{ app_namespace }}.svc:8080"
keycloak_sso_realm: "tackle"
keycloak_sso_req_passwd_update: true
keycloak_sso_hub_client_id: "tackle-hub"
keycloak_sso_hub_client_secret: "tackle"

ui_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_TACKLE_UI') }}"
ui_component_name: "ui"
ui_service_name: "{{ app_name }}-{{ ui_component_name }}"
ui_configmap_name: "{{ ui_service_name }}-config"
ui_deployment_name: "{{ ui_service_name }}"
ui_deployment_replicas: "1"
ui_container_name: "{{ ui_service_name }}"
ui_container_limits_cpu: "500m"
ui_container_limits_memory: "800Mi"
ui_container_requests_cpu: "100m"
ui_container_requests_memory: "350Mi"
ui_ingress_name: "{{ app_name }}"
ui_ingress_proxy_body_size: "500m"
ui_route_name: "{{ app_name }}"
ui_tls_enabled: false
ui_route_tls_termination: "edge"
ui_route_tls_insecure_termination_policy: "Redirect"
ui_tls_secret_name: "{{ ui_service_name }}-serving-cert"

admin_fqin: "{{ lookup('env', 'RELATED_IMAGE_ADDON_ADMIN') }}"
admin_name: "admin"
admin_component_name: "addon"
admin_service_name: "{{ app_name }}-{{ admin_name }}-{{ admin_component_name }}"
admin_container_requests_cpu: "50m"
admin_container_requests_memory: "50Mi"

windup_fqin: "{{ lookup('env', 'RELATED_IMAGE_ADDON_WINDUP') }}"
windup_name: "windup"
windup_component_name: "addon"
windup_service_name: "{{ app_name }}-{{ windup_name }}-{{ windup_component_name }}"
windup_container_requests_cpu: "500m"
windup_container_requests_memory: "2Gi"

maven_name: "maven"
maven_data_volume_size: "100Gi"
maven_data_volume_name: "{{ app_name }}-{{ maven_name }}-data"
maven_data_volume_claim_name: "{{ app_name }}-{{ maven_name }}-volume-claim"

# RH-SSO
rhsso_name: "rhsso"
rhsso_service_name: "{{ app_name }}-{{ rhsso_name }}"
rhsso_external_access: false
